vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: /articles/images
            upload_destination: '%kernel.project_dir%/public/articles/images'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
